export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const CLEAR_BOOKS = 'CLEAR_BOOKS';
export const SORT_BOOKS_BY_TITLE = 'SORT_BOOKS_BY_TITLE';
export const SORT_BOOKS_BY_PUBLISHED_YEAR = 'SORT_BOOKS_BY_PUBLISHED_YEAR';
export const BOOK_ERROR = 'BOOK_ERROR';
